import builtins
from typing import TYPE_CHECKING

from griddy.core._import import dynamic_import

if TYPE_CHECKING:
    from griddy.pfr.models.entities.coach_profile import (
        ChallengeResult,
        ChallengeResultTypedDict,
        CoachBio,
        CoachBioTypedDict,
        CoachingHistoryEntry,
        CoachingHistoryEntryTypedDict,
        CoachingRank,
        CoachingRankTypedDict,
        CoachingResult,
        CoachingResultTotal,
        CoachingResultTotalTypedDict,
        CoachingResultTypedDict,
        CoachingTreeEntry,
        CoachingTreeEntryTypedDict,
        CoachProfile,
        CoachProfileTypedDict,
    )
    from griddy.pfr.models.entities.game_details import (
        Drive,
        DriveTypedDict,
        ExpectedPoints,
        ExpectedPointsTypedDict,
        GameDetails,
        GameDetailsTypedDict,
        LinescoreEntry,
        LinescoreEntryTypedDict,
        PlayerDefense,
        PlayerDefenseTypedDict,
        PlayerKicking,
        PlayerKickingTypedDict,
        PlayerOffense,
        PlayerOffenseTypedDict,
        PlayerReturn,
        PlayerReturnTypedDict,
        Scorebox,
        ScoreboxMeta,
        ScoreboxMetaTypedDict,
        ScoreboxTeam,
        ScoreboxTeamTypedDict,
        ScoreboxTypedDict,
        ScoringPlay,
        ScoringPlayTypedDict,
        SnapCount,
        SnapCountTypedDict,
        Starter,
        StarterTypedDict,
    )
    from griddy.pfr.models.entities.official_profile import (
        OfficialBio,
        OfficialBioTypedDict,
        OfficialGame,
        OfficialGameTypedDict,
        OfficialProfile,
        OfficialProfileTypedDict,
        OfficialSeasonStat,
        OfficialSeasonStatTypedDict,
    )
    from griddy.pfr.models.entities.player_profile import (
        BirthPlace,
        BirthPlaceTypedDict,
        DraftInfo,
        DraftInfoTypedDict,
        JerseyNumber,
        JerseyNumberTypedDict,
        PlayerBio,
        PlayerBioTypedDict,
        PlayerNames,
        PlayerNamesTypedDict,
        PlayerProfile,
        PlayerProfileTypedDict,
        PlayerStatistics,
        PlayerStatisticsTypedDict,
        RoundAndOverall,
        RoundAndOverallTypedDict,
        Transaction,
        TransactionTypedDict,
    )
    from griddy.pfr.models.entities.schedule_game import (
        ScheduleGame,
        ScheduleGameTypedDict,
    )
    from griddy.pfr.models.entities.season import (
        ConferenceStanding,
        ConferenceStandingTypedDict,
        PlayoffGame,
        PlayoffGameTypedDict,
        PlayoffStanding,
        PlayoffStandingTypedDict,
        SeasonOverview,
        SeasonOverviewTypedDict,
        SeasonStats,
        SeasonStatsTypedDict,
        WeekGame,
        WeekGameTypedDict,
        WeekSummary,
        WeekSummaryTypedDict,
    )
    from griddy.pfr.models.entities.security import Security, SecurityTypedDict
    from griddy.pfr.models.entities.stadium import (
        StadiumBestGame,
        StadiumBestGameTypedDict,
        StadiumBio,
        StadiumBioTypedDict,
        StadiumGameLeader,
        StadiumGameLeaderTypedDict,
        StadiumGameSummary,
        StadiumGameSummaryTypedDict,
        StadiumLeader,
        StadiumLeaderTypedDict,
        StadiumProfile,
        StadiumProfileTypedDict,
        StadiumTeam,
        StadiumTeamTypedDict,
    )
    from griddy.pfr.models.entities.team_franchise import (
        Franchise,
        FranchiseLeader,
        FranchiseLeaderTypedDict,
        FranchiseMeta,
        FranchiseMetaTypedDict,
        FranchiseSeasonRecord,
        FranchiseSeasonRecordTypedDict,
        FranchiseTypedDict,
    )
    from griddy.pfr.models.entities.team_season import (
        SeasonGame,
        SeasonGameTypedDict,
        TeamSeason,
        TeamSeasonMeta,
        TeamSeasonMetaTypedDict,
        TeamSeasonTypedDict,
    )

__all__ = [
    "ChallengeResult",
    "ChallengeResultTypedDict",
    "CoachBio",
    "CoachBioTypedDict",
    "CoachingHistoryEntry",
    "CoachingHistoryEntryTypedDict",
    "CoachingRank",
    "CoachingRankTypedDict",
    "CoachingResult",
    "CoachingResultTotal",
    "CoachingResultTotalTypedDict",
    "CoachingResultTypedDict",
    "CoachingTreeEntry",
    "CoachingTreeEntryTypedDict",
    "CoachProfile",
    "CoachProfileTypedDict",
    "OfficialBio",
    "OfficialBioTypedDict",
    "OfficialGame",
    "OfficialGameTypedDict",
    "OfficialProfile",
    "OfficialProfileTypedDict",
    "OfficialSeasonStat",
    "OfficialSeasonStatTypedDict",
    "Drive",
    "DriveTypedDict",
    "ExpectedPoints",
    "ExpectedPointsTypedDict",
    "GameDetails",
    "GameDetailsTypedDict",
    "LinescoreEntry",
    "LinescoreEntryTypedDict",
    "PlayerDefense",
    "PlayerDefenseTypedDict",
    "PlayerKicking",
    "PlayerKickingTypedDict",
    "PlayerOffense",
    "PlayerOffenseTypedDict",
    "PlayerReturn",
    "PlayerReturnTypedDict",
    "BirthPlace",
    "BirthPlaceTypedDict",
    "DraftInfo",
    "DraftInfoTypedDict",
    "JerseyNumber",
    "JerseyNumberTypedDict",
    "PlayerBio",
    "PlayerBioTypedDict",
    "PlayerNames",
    "PlayerNamesTypedDict",
    "PlayerProfile",
    "PlayerProfileTypedDict",
    "PlayerStatistics",
    "PlayerStatisticsTypedDict",
    "RoundAndOverall",
    "RoundAndOverallTypedDict",
    "ScheduleGame",
    "ScheduleGameTypedDict",
    "ConferenceStanding",
    "ConferenceStandingTypedDict",
    "PlayoffGame",
    "PlayoffGameTypedDict",
    "PlayoffStanding",
    "PlayoffStandingTypedDict",
    "SeasonOverview",
    "SeasonOverviewTypedDict",
    "SeasonStats",
    "SeasonStatsTypedDict",
    "WeekGame",
    "WeekGameTypedDict",
    "WeekSummary",
    "WeekSummaryTypedDict",
    "StadiumBestGame",
    "StadiumBestGameTypedDict",
    "StadiumBio",
    "StadiumBioTypedDict",
    "StadiumGameLeader",
    "StadiumGameLeaderTypedDict",
    "StadiumGameSummary",
    "StadiumGameSummaryTypedDict",
    "StadiumLeader",
    "StadiumLeaderTypedDict",
    "StadiumProfile",
    "StadiumProfileTypedDict",
    "StadiumTeam",
    "StadiumTeamTypedDict",
    "Scorebox",
    "ScoreboxMeta",
    "ScoreboxMetaTypedDict",
    "ScoreboxTeam",
    "ScoreboxTeamTypedDict",
    "ScoreboxTypedDict",
    "ScoringPlay",
    "ScoringPlayTypedDict",
    "FranchiseLeader",
    "FranchiseLeaderTypedDict",
    "FranchiseMeta",
    "FranchiseMetaTypedDict",
    "FranchiseSeasonRecord",
    "FranchiseSeasonRecordTypedDict",
    "SeasonGame",
    "SeasonGameTypedDict",
    "Security",
    "SecurityTypedDict",
    "SnapCount",
    "SnapCountTypedDict",
    "Starter",
    "StarterTypedDict",
    "Franchise",
    "FranchiseTypedDict",
    "TeamSeason",
    "TeamSeasonMeta",
    "TeamSeasonMetaTypedDict",
    "TeamSeasonTypedDict",
    "Transaction",
    "TransactionTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "ChallengeResult": ".entities.coach_profile",
    "ChallengeResultTypedDict": ".entities.coach_profile",
    "CoachBio": ".entities.coach_profile",
    "CoachBioTypedDict": ".entities.coach_profile",
    "CoachingHistoryEntry": ".entities.coach_profile",
    "CoachingHistoryEntryTypedDict": ".entities.coach_profile",
    "CoachingRank": ".entities.coach_profile",
    "CoachingRankTypedDict": ".entities.coach_profile",
    "CoachingResult": ".entities.coach_profile",
    "CoachingResultTotal": ".entities.coach_profile",
    "CoachingResultTotalTypedDict": ".entities.coach_profile",
    "CoachingResultTypedDict": ".entities.coach_profile",
    "CoachingTreeEntry": ".entities.coach_profile",
    "CoachingTreeEntryTypedDict": ".entities.coach_profile",
    "CoachProfile": ".entities.coach_profile",
    "CoachProfileTypedDict": ".entities.coach_profile",
    "OfficialBio": ".entities.official_profile",
    "OfficialBioTypedDict": ".entities.official_profile",
    "OfficialGame": ".entities.official_profile",
    "OfficialGameTypedDict": ".entities.official_profile",
    "OfficialProfile": ".entities.official_profile",
    "OfficialProfileTypedDict": ".entities.official_profile",
    "OfficialSeasonStat": ".entities.official_profile",
    "OfficialSeasonStatTypedDict": ".entities.official_profile",
    "BirthPlace": ".entities.player_profile",
    "BirthPlaceTypedDict": ".entities.player_profile",
    "DraftInfo": ".entities.player_profile",
    "DraftInfoTypedDict": ".entities.player_profile",
    "Drive": ".entities.game_details",
    "DriveTypedDict": ".entities.game_details",
    "ExpectedPoints": ".entities.game_details",
    "ExpectedPointsTypedDict": ".entities.game_details",
    "GameDetails": ".entities.game_details",
    "GameDetailsTypedDict": ".entities.game_details",
    "JerseyNumber": ".entities.player_profile",
    "JerseyNumberTypedDict": ".entities.player_profile",
    "LinescoreEntry": ".entities.game_details",
    "LinescoreEntryTypedDict": ".entities.game_details",
    "PlayerBio": ".entities.player_profile",
    "PlayerBioTypedDict": ".entities.player_profile",
    "PlayerDefense": ".entities.game_details",
    "PlayerDefenseTypedDict": ".entities.game_details",
    "PlayerNames": ".entities.player_profile",
    "PlayerNamesTypedDict": ".entities.player_profile",
    "PlayerKicking": ".entities.game_details",
    "PlayerKickingTypedDict": ".entities.game_details",
    "PlayerOffense": ".entities.game_details",
    "PlayerOffenseTypedDict": ".entities.game_details",
    "PlayerProfile": ".entities.player_profile",
    "PlayerProfileTypedDict": ".entities.player_profile",
    "PlayerReturn": ".entities.game_details",
    "PlayerReturnTypedDict": ".entities.game_details",
    "PlayerStatistics": ".entities.player_profile",
    "PlayerStatisticsTypedDict": ".entities.player_profile",
    "RoundAndOverall": ".entities.player_profile",
    "RoundAndOverallTypedDict": ".entities.player_profile",
    "Scorebox": ".entities.game_details",
    "ScoreboxMeta": ".entities.game_details",
    "ScoreboxMetaTypedDict": ".entities.game_details",
    "ScoreboxTeam": ".entities.game_details",
    "ScoreboxTeamTypedDict": ".entities.game_details",
    "ScoreboxTypedDict": ".entities.game_details",
    "ScoringPlay": ".entities.game_details",
    "ScoringPlayTypedDict": ".entities.game_details",
    "ScheduleGame": ".entities.schedule_game",
    "ScheduleGameTypedDict": ".entities.schedule_game",
    "ConferenceStanding": ".entities.season",
    "ConferenceStandingTypedDict": ".entities.season",
    "PlayoffGame": ".entities.season",
    "PlayoffGameTypedDict": ".entities.season",
    "PlayoffStanding": ".entities.season",
    "PlayoffStandingTypedDict": ".entities.season",
    "SeasonOverview": ".entities.season",
    "SeasonOverviewTypedDict": ".entities.season",
    "SeasonStats": ".entities.season",
    "SeasonStatsTypedDict": ".entities.season",
    "WeekGame": ".entities.season",
    "WeekGameTypedDict": ".entities.season",
    "WeekSummary": ".entities.season",
    "WeekSummaryTypedDict": ".entities.season",
    "StadiumBestGame": ".entities.stadium",
    "StadiumBestGameTypedDict": ".entities.stadium",
    "StadiumBio": ".entities.stadium",
    "StadiumBioTypedDict": ".entities.stadium",
    "StadiumGameLeader": ".entities.stadium",
    "StadiumGameLeaderTypedDict": ".entities.stadium",
    "StadiumGameSummary": ".entities.stadium",
    "StadiumGameSummaryTypedDict": ".entities.stadium",
    "StadiumLeader": ".entities.stadium",
    "StadiumLeaderTypedDict": ".entities.stadium",
    "StadiumProfile": ".entities.stadium",
    "StadiumProfileTypedDict": ".entities.stadium",
    "StadiumTeam": ".entities.stadium",
    "StadiumTeamTypedDict": ".entities.stadium",
    "FranchiseLeader": ".entities.team_franchise",
    "FranchiseLeaderTypedDict": ".entities.team_franchise",
    "FranchiseMeta": ".entities.team_franchise",
    "FranchiseMetaTypedDict": ".entities.team_franchise",
    "FranchiseSeasonRecord": ".entities.team_franchise",
    "FranchiseSeasonRecordTypedDict": ".entities.team_franchise",
    "SeasonGame": ".entities.team_season",
    "SeasonGameTypedDict": ".entities.team_season",
    "Security": ".entities.security",
    "SecurityTypedDict": ".entities.security",
    "SnapCount": ".entities.game_details",
    "SnapCountTypedDict": ".entities.game_details",
    "Starter": ".entities.game_details",
    "StarterTypedDict": ".entities.game_details",
    "Franchise": ".entities.team_franchise",
    "FranchiseTypedDict": ".entities.team_franchise",
    "TeamSeason": ".entities.team_season",
    "TeamSeasonMeta": ".entities.team_season",
    "TeamSeasonMetaTypedDict": ".entities.team_season",
    "TeamSeasonTypedDict": ".entities.team_season",
    "Transaction": ".entities.player_profile",
    "TransactionTypedDict": ".entities.player_profile",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
